---
apiVersion: v1
kind: Secret
metadata:
  name: maas-instance-registrations
  labels:
    app.kubernetes.io/instance: {{ .Values.SERVICE_NAME }}
    app.kubernetes.io/managed-by: "helm"
    deployment.qubership.org/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
data:
{{ if .Values.MAAS_KAFKA_INSTANCE_BODY }}
  maas-kafka-instance-body: {{ .Values.MAAS_KAFKA_INSTANCE_BODY | b64enc }}
{{ end }}
{{ if .Values.MAAS_KAFKA_INSTANCE_BODY_2 }}
  maas-kafka-instance-body-2: {{ .Values.MAAS_KAFKA_INSTANCE_BODY_2 | b64enc }}
{{ end }}
{{ if .Values.MAAS_RABBIT_INSTANCE_BODY }}
  maas-rabbit-instance-body: {{ .Values.MAAS_RABBIT_INSTANCE_BODY | b64enc }}
{{ end }}
{{ if .Values.MAAS_RABBIT_INSTANCE_BODY_2 }}
  maas-rabbit-instance-body-2: {{ .Values.MAAS_RABBIT_INSTANCE_BODY_2 | b64enc }}
{{ end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: maas-accounts
  labels:
    app.kubernetes.io/instance: {{ .Values.SERVICE_NAME }}
    app.kubernetes.io/managed-by: "helm"
    deployment.qubership.org/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
data:
  manager-username:  {{ .Values.MAAS_ACCOUNT_MANAGER_USERNAME | b64enc }}
  manager-password: {{ .Values.MAAS_ACCOUNT_MANAGER_PASSWORD | b64enc }}
  deployer-username: {{ .Values.MAAS_DEPLOYER_CLIENT_USERNAME | b64enc }}
  deployer-password: {{ .Values.MAAS_DEPLOYER_CLIENT_PASSWORD | b64enc }}
